name: Batch Processing Pipeline

on:
  workflow_dispatch: { }
  push: { }


jobs:
  find-files:
    runs-on: ubuntu-latest
    outputs:
      inputs: ${{ steps.bash.outputs.inputs }}
    steps:
      - uses: actions/checkout@v4
      - id: bash
        run: |
          INP_ARR=["$(ls ./inputs -1 | sed 's/^/"/;s/$/"/;s/$/,/' | tr -d '\n' | sed 's/,$//')"]
          echo "inputs=$INP_ARR" >> "$GITHUB_OUTPUT"
          echo $INP_ARR

  concurrent:
    needs: find-files
    strategy:
      matrix:
        inputs: ${{fromJSON(needs.find-files.outputs.inputs)}}
    uses: skypaw/file-converter/.github/workflows/reusable.yml@main
    with:
      input-file: ${{ matrix.inputs }}
