on:
  workflow_call:
    inputs:
      input-file:
        required: true
        type: string

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip
      - run: pip install -r requirements.txt
      - run: mkdir ./output
      - run: python main.py -i ./inputs/${{ inputs.input-file }} -o ./output/${{ inputs.input-file }}-output.txt
      - name: Upload processed file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.input-file }}
          path: output/
